version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/volumes/database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON_URL: ${SERVER_HOST}/api/v1/swagger
    ports:
      - ${SWAGGER_PORT}:8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_DATABASES: ${REDIS_DATABASES}