version: '3.1'
services:
  db:
    env_file:
      - .env
      - .env.local
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON_URL: ${SERVER_URL}/swagger/api
    ports:
      - ${SWAGGER_PORT}:8080